spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/ledgercore_dev}
logging:
  level:
    com.ledgercore: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
